export type ServiceCategory = 'repair' | 'care' | 'resizing' | 'stones' | 'inspection';

export interface ServiceItem {
	id: string;
	category: ServiceCategory;
	categoryLabel: string;
	name: string;
	tagline: string;
	description: string;
	turnaroundTime: string;
	benchMethod: string;
	startingPrice: number;
	priceUnit?: string;
	riskLevel: 'Minimal' | 'Micro-Precision Bench' | 'High-Heirloom Complexity';
	assurances: string[];
	badge?: string;
}

export const SERVICE_CATEGORIES = [
	{ id: 'all', label: 'All Services', description: 'Explore full atelier workshop capabilities' },
	{ id: 'repair', label: 'Repair', description: 'Laser micro-welding, broken link soldering & structural rebuilds' },
	{ id: 'care', label: 'Care & Restoration', description: 'Multi-stage ultrasonic cleaning, electrolytic polish & antique patina' },
	{ id: 'resizing', label: 'Resizing & Modification', description: 'Hallmark-safe ring sizing, bangle adjustment & custom conversions' },
	{ id: 'stones', label: 'Stone Services', description: 'Master prong/Jadau setting, loose stone tightening & GIA replacement' },
	{ id: 'inspection', label: 'Inspection & Diagnostics', description: '10x microscope assay diagnostics, damage assessment & bench triage' },
] as const;

export const SERVICES_LIST: ServiceItem[] = [
	// ==================== 1. REPAIR (7 Services) ====================
	{
		id: 'ring-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Ring Repair',
		tagline: 'Band fracture fusion, shank reinforcement & deformed ring re-rounding',
		description: 'Precision laser welding restores cracked or deformed shanks back to perfect circular calibration without melting adjoining hallmarks or loosening diamond settings.',
		turnaroundTime: 'Same Day (3–4 hrs)',
		benchMethod: 'PUK 6 Laser Cold Welding & Precision Mandrel Re-Rounding',
		startingPrice: 1200,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['0.001g weight balance slip', 'Hallmark preserved', 'Prong tension re-check'],
		badge: 'Popular',
	},
	{
		id: 'chain-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Chain Repair',
		tagline: 'Broken link soldering, hollow rope reinforcement & custom end-caps',
		description: 'Seamless link-by-link microscopic soldering for 22K and 18K solid and hollow chains with zero discoloration or stiff joint freezing.',
		turnaroundTime: 'Same Day (2 hrs)',
		benchMethod: 'Micro-Pulse Argon Laser Joint Welding',
		startingPrice: 850,
		riskLevel: 'Minimal',
		assurances: ['Zero stiffness guarantee', 'Color-matched alloy solder', 'Tensile strength pull test'],
		badge: 'Quick Service',
	},
	{
		id: 'necklace-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Necklace Repair',
		tagline: 'Choker hinge rebuilding, broken nakashi motifs & structural integrity',
		description: 'Expert repair of ornate traditional harams and chokers. Rebuilds worn-out interlink pins, bent wirework, and damaged filigree joints.',
		turnaroundTime: '24–48 Hours',
		benchMethod: 'Artisan Micro-Pliers & Heat-Shielded Laser Fusion',
		startingPrice: 1800,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Motif alignment guarantee', 'Heat-sensitive gem shield applied', 'Flexibility restored'],
	},
	{
		id: 'bangle-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Bangle Repair',
		tagline: 'Dented hollow kadas, cracked hinge joints & screw-lock replacement',
		description: 'Re-rounding ovaled bangles, removing internal hollow dents using hydraulic pressure benches, and repairing antique screw-lock mechanism clasps.',
		turnaroundTime: '24 Hours',
		benchMethod: 'Precision Bangle Expander & Hinge Pin Machining',
		startingPrice: 1500,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Original contour restored', 'Screw-thread re-tapping', 'Zero loss audit'],
	},
	{
		id: 'bracelet-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Bracelet Repair',
		tagline: 'Tennis bracelet link re-pinning, safety catch rebuilds & clasp tensioning',
		description: 'Micro-pin replacement on articulated diamond tennis bracelets and charm bracelets, ensuring each link swivels freely without catching clothing.',
		turnaroundTime: 'Same Day (4 hrs)',
		benchMethod: 'Microscopic Riveting & Safety Clasp Spring Re-tensioning',
		startingPrice: 1400,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Double safety catch test', 'Diamond seat inspection', 'Ultrasonic rinse included'],
	},
	{
		id: 'earring-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Earring Repair',
		tagline: 'Broken ear posts, South Indian screw back re-threading & dangling tassel fixes',
		description: 'Fast replacement of snapped earring stems, re-threading of traditional screw backs (Thiruvani), and reinforcement of heavy jhumka hanging hoops.',
		turnaroundTime: 'Same Day (2 hrs)',
		benchMethod: '22K Gold Post Fusion & Thread Gauge Milling',
		startingPrice: 750,
		riskLevel: 'Minimal',
		assurances: ['Hypoallergenic finish', 'Exact thread match', 'Comfort gauge calibration'],
		badge: 'Express',
	},
	{
		id: 'other-jewellery-repair',
		category: 'repair',
		categoryLabel: 'Repair',
		name: 'Other Jewellery Repair',
		tagline: 'Vaddanams, mangtikkas, brooches, cuff links & heirloom oddities',
		description: 'Custom atelier bench restoration for antique waist belts (Oddiyanam), armlets (Vanki), hair ornaments, and rare heirloom jewellery artifacts.',
		turnaroundTime: '2–5 Days',
		benchMethod: 'Hand-Forging & Historical Goldsmithing Bench Restorations',
		startingPrice: 2500,
		riskLevel: 'High-Heirloom Complexity',
		assurances: ['Antique patina protection', 'Structural re-engineering', 'Vault custody logging'],
	},

	// ==================== 2. CARE & RESTORATION (5 Services) ====================
	{
		id: 'cleaning',
		category: 'care',
		categoryLabel: 'Care & Restoration',
		name: 'Ultrasonic Deep Cleaning',
		tagline: 'Multi-stage sonic wave sanitization removing decades of lotion & dust buildup',
		description: 'Jewellery undergoes a three-stage ultrasonic fluid bath using organic bio-detergents that safely loosen calcified dirt behind stones without dislodging settings.',
		turnaroundTime: '30 Minutes (While You Wait)',
		benchMethod: '40kHz Transducer Ultrasonic Bath & 100 PSI Dry Steam Jet',
		startingPrice: 450,
		riskLevel: 'Minimal',
		assurances: ['Gem safe temperature controls', 'Microscope pre-check', 'Instant sparkle revitalization'],
		badge: 'Complimentary on Inspection',
	},
	{
		id: 'polishing',
		category: 'care',
		categoryLabel: 'Care & Restoration',
		name: 'High-Lustre Gold Polishing',
		tagline: 'Multi-grade Tripoli & Rouge buffing with zero measurable gold loss',
		description: 'Micro-abrasive polishing removes surface micro-scratches and restores mirror-bright shine or traditional satin matte finishes with strict weight accounting.',
		turnaroundTime: 'Same Day (2 hrs)',
		benchMethod: 'Dual-Speed Cotton Buffing Lathe & Dialux Rouge Compound',
		startingPrice: 650,
		riskLevel: 'Minimal',
		assurances: ['Gross weight tracked to 0.001g', 'Edges remain crisp', 'No hallmark abrasion'],
	},
	{
		id: 'restoration',
		category: 'care',
		categoryLabel: 'Care & Restoration',
		name: 'Full Heirloom Restoration',
		tagline: 'Complete structural rejuvenation for multi-generational family treasures',
		description: 'Deep revitalization of aged, bent, or worn jewellery. We re-tighten every stone, re-weld thin spots, restore engraved borders, and finish with authentic polish.',
		turnaroundTime: '3–5 Days',
		benchMethod: 'Full Goldsmith Bench Teardown, Reinforcement & Refinishing',
		startingPrice: 4500,
		riskLevel: 'High-Heirloom Complexity',
		assurances: ['Before & after digital photo dossier', 'Zero loss certificate', 'Lifetime bench guarantee'],
		badge: 'Atelier Signature',
	},
	{
		id: 'antique-restoration',
		category: 'care',
		categoryLabel: 'Care & Restoration',
		name: 'Antique & Nakashi Patina Restoration',
		tagline: 'Preserving historical oxidation, sacred temple motifs & meenakari enamel',
		description: 'Unlike standard polishing that ruins antique finishes, our master artisans selectively clean raised highlights while preserving centuries-old antique oxidized patina.',
		turnaroundTime: '4–7 Days',
		benchMethod: 'Micro-Chisel Resharpening & Controlled Sulfide Patination',
		startingPrice: 5500,
		riskLevel: 'High-Heirloom Complexity',
		assurances: ['Sacred iconography preserved', 'Enamel micro-repair', 'Historical value conserved'],
	},
	{
		id: 'jewellery-maintenance',
		category: 'care',
		categoryLabel: 'Care & Restoration',
		name: 'Annual Vault Maintenance Plan',
		tagline: 'Preventative care, ultrasonic rinse, prong tightening & insured vault check',
		description: 'Comprehensive annual health inspection for your bridal treasury. Keeps clasps crisp, prongs tight, and stones brilliantly clean before big celebratory occasions.',
		turnaroundTime: 'Same Day (3 hrs)',
		benchMethod: 'Comprehensive 12-Point Goldsmith Bench Diagnostic Protocol',
		startingPrice: 1999,
		riskLevel: 'Minimal',
		assurances: ['Detailed condition report', 'Loose stone prevention', 'Complimentary storage pouch'],
	},

	// ==================== 3. RESIZING & MODIFICATION (6 Services) ====================
	{
		id: 'ring-resizing',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Hallmark-Safe Ring Resizing',
		tagline: 'Size up or down with laser fusion, zero seam lines & hallmark preservation',
		description: 'We resize gold, platinum, and diamond rings up to 4 sizes larger or smaller. A matching purity gold insert is laser-welded seamlessly with no visible line or hallmark disruption.',
		turnaroundTime: '24 Hours',
		benchMethod: 'Laser Micro-Cold Welding & Precision Ring Sizing Benches',
		startingPrice: 1400,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Gold weight adjustment receipt', 'Hallmark preserved', 'True circular symmetry'],
		badge: 'Most Requested',
	},
	{
		id: 'bangle-size-adjustment',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Bangle Size Adjustment',
		tagline: 'Inner diameter expansion or contraction for solid & hinged bangles',
		description: 'Adjusting antique or heirloom bangles to fit comfortably. Solid bangles are cold-drawn or spliced with hallmarked 22K alloy to widen inner circumference by millimeters.',
		turnaroundTime: '2–3 Days',
		benchMethod: 'Circular Core Expander & Micro Laser Splicing',
		startingPrice: 2200,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Pattern continuity maintained', 'Zero oval distortion', 'Exact mm wrist fit'],
	},
	{
		id: 'chain-length-adjustment',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Chain Length Adjustment',
		tagline: 'Shortening, adding extension loops, or lengthening with matched links',
		description: 'Shorten a rope or box chain cleanly, or add adjustable jump ring stations (16", 18", 20") so a single chain can be worn at multiple neckline heights.',
		turnaroundTime: 'Same Day (2 hrs)',
		benchMethod: 'Micro-Joint Cutting & Laser Extension Jump Ring Solder',
		startingPrice: 950,
		riskLevel: 'Minimal',
		assurances: ['Removed gold returned to customer', 'Color-matched jump rings', 'Tensile tested'],
	},
	{
		id: 'necklace-length-adjustment',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Necklace Length & Dori Adjustment',
		tagline: 'Hand-woven Zari thread replacement or solid gold chain extension',
		description: 'Replace worn, frayed silk necklace cords (Doris) with rich hand-woven Zari cords, or convert a cord-back necklace into a permanent solid gold adjustable link chain.',
		turnaroundTime: 'Same Day (3 hrs)',
		benchMethod: 'Artisan Zari Cord Stringing & 22K Gold Back-Chain Fusion',
		startingPrice: 1100,
		riskLevel: 'Minimal',
		assurances: ['Hand-dyed color match', 'Smooth slide tassel', 'Reinforced end-knots'],
	},
	{
		id: 'design-modification',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Design Modification & Redesign',
		tagline: 'Modernizing heavy, unworn pieces into contemporary wearable daily fine jewellery',
		description: 'Have a heavy heirloom necklace you never wear? Our designers and karigars will sketch ways to split it into a modern pendant, delicate bracelet, and matching stud earrings.',
		turnaroundTime: '7–14 Days',
		benchMethod: 'CAD 3D Modeling, Wax Carving & Karigar Hand Fabrication',
		startingPrice: 6500,
		riskLevel: 'High-Heirloom Complexity',
		assurances: ['3D photorealistic CAD render', 'Retain original sentimental stones', 'Full bullion credit'],
		badge: 'Bespoke Transformation',
	},
	{
		id: 'jewellery-conversion',
		category: 'resizing',
		categoryLabel: 'Resizing & Modification',
		name: 'Jewellery Conversion',
		tagline: 'Earrings to pendants, brooches to rings, long harams to detachable chokers',
		description: 'Smart mechanical transformations allowing traditional ornaments to double as modern wearable pieces with modular hidden clips and interchangeable bails.',
		turnaroundTime: '5–7 Days',
		benchMethod: 'Modular Precision Catch Engineering & Concealed Bails',
		startingPrice: 3800,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Seamless modular mechanism', 'Zero aesthetic compromise', 'Multi-wear versatility'],
	},

	// ==================== 4. STONE SERVICES (6 Services) ====================
	{
		id: 'stone-replacement',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Certified Stone Replacement',
		tagline: 'Sourcing exact matching diamonds, rubies, emeralds, and Syndicate Polki',
		description: 'When a stone has fallen out, we match the exact color, clarity, cut, and millimeter dimension using our extensive vault of natural Burmese rubies, Zambian emeralds, and GIA diamonds.',
		turnaroundTime: '2–4 Days',
		benchMethod: 'Calibrated Gem Sourcing & Precision Seat Re-Carving',
		startingPrice: 1600,
		priceUnit: '+ stone cost',
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Exact color & facet match', 'Gemologist certificate', 'Zero gap setting'],
		badge: 'Vault Sourced',
	},
	{
		id: 'stone-setting',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Master Gemstone Setting',
		tagline: 'Micro-Pave, Channel, Bezel, Bar, and Traditional Jadau Kundan foil setting',
		description: 'Performed under high-magnification stereomicroscopes by master setters. Ensures each stone is seated level, secure against daily bumps, with no light obstruction.',
		turnaroundTime: '24–48 Hours',
		benchMethod: 'Meiji 10x-40x Gemologist Bench Microscope & Pneumatic Gravers',
		startingPrice: 1800,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Tap test verification', 'Zero snag prong polish', 'Full light refraction'],
	},
	{
		id: 'stone-resetting',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Diamond & Solitaire Resetting',
		tagline: 'Transfer your cherished diamond into a fresh modern bespoke gold setting',
		description: 'Safely unmount your legacy diamond from an outdated or worn setting and reset it into a newly sculpted solitaire ring, pendant, or tennis mount.',
		turnaroundTime: '3–5 Days',
		benchMethod: 'Cold-Lever Extraction & Custom Prong Hand-Forging',
		startingPrice: 2800,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['GIA Inscription verified in your presence', 'Zero girdle stress', 'New mount hallmarked'],
	},
	{
		id: 'loose-stone-repair',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Loose Stone Tightening & Re-Tipping',
		tagline: 'Rebuilding worn prongs with micro-laser droplets before stones fall out',
		description: 'If your stone clicks or rattles, the prongs have worn down. We build up fresh 22K or 18K gold crowns onto the prongs and burnish them securely over the gem.',
		turnaroundTime: 'Same Day (2–3 hrs)',
		benchMethod: 'Micro Laser Gold Wire Welding & Beading Tool Burnish',
		startingPrice: 950,
		riskLevel: 'Micro-Precision Bench',
		assurances: ['Prongs rebuilt with virgin alloy', 'Audio rattle test', 'Prevents costly stone loss'],
		badge: 'Preventative Care',
	},
	{
		id: 'missing-stone-replacement',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Missing Stone Replacement',
		tagline: 'Re-cutting missing melee diamonds and uncut Jadau Polki segments',
		description: 'Custom lapidary cutting for complex shapes (baguettes, marquise, uncut Polki slice) to fit irregularly damaged or antique handcrafted seats.',
		turnaroundTime: '3–5 Days',
		benchMethod: 'Custom Lapidary Faceting & Silver Foil Jadau Setting',
		startingPrice: 2100,
		priceUnit: '+ stone cost',
		riskLevel: 'High-Heirloom Complexity',
		assurances: ['Custom cut to existing seat', 'Original aesthetic matched', 'Secure lock-in'],
	},
	{
		id: 'stone-inspection',
		category: 'stones',
		categoryLabel: 'Stone Services',
		name: 'Microscopic Stone Inspection',
		tagline: '10x-40x HD stereomicroscope examination checking table, girdle & prongs',
		description: 'Watch on our in-salon HD screen as our gemologist audits your stones under high magnification. Detects micro-fractures, chipped girdles, and loose prongs early.',
		turnaroundTime: '15 Minutes (In-Salon)',
		benchMethod: 'Meiji Stereo Zoom Microscope with 4K HDMI Live Projection',
		startingPrice: 0,
		riskLevel: 'Minimal',
		assurances: ['Live customer viewing', 'High-res digital capture', 'Zero obligation advice'],
		badge: 'Complimentary In-Salon',
	},

	// ==================== 5. INSPECTION & DIAGNOSTICS (4 Services) ====================
	{
		id: 'jewellery-inspection',
		category: 'inspection',
		categoryLabel: 'Inspection & Diagnostics',
		name: 'Comprehensive Vault Jewellery Inspection',
		tagline: '18-point engineering audit checking metal fatigue, solder joints & hallmark',
		description: 'A multi-point diagnostic check examining clasp tension, hinge play, hallmark authenticity, metal wear-through, and structural vulnerabilities.',
		turnaroundTime: '30 Minutes',
		benchMethod: 'Caliper Measurements, Loupe Audit & Ultrasonic Acoustic Test',
		startingPrice: 500,
		riskLevel: 'Minimal',
		assurances: ['Digital safety passport', 'Prioritized action list', 'Complimentary ultrasonic polish'],
	},
	{
		id: 'damage-assessment',
		category: 'inspection',
		categoryLabel: 'Inspection & Diagnostics',
		name: 'Accidental Damage Assessment',
		tagline: 'Formal diagnostic report for insurance, inheritance, or high-impact claims',
		description: 'Crushed underfoot, caught in a car door, or snapped during festivities? Our master goldsmith evaluates internal crystal fatigue and feasibility of restoration.',
		turnaroundTime: '24 Hours',
		benchMethod: 'Metallurgical Stress Analysis & Feasibility Modeling',
		startingPrice: 1200,
		riskLevel: 'Minimal',
		assurances: ['Official stamped report', 'Transparent scrap vs salvage breakdown', 'CAD reconstruction estimate'],
	},
	{
		id: 'repair-assessment',
		category: 'inspection',
		categoryLabel: 'Inspection & Diagnostics',
		name: 'Second Opinion & Repair Assessment',
		tagline: 'Unsure if another jeweler’s quote or repair technique was correct?',
		description: 'Bring in work done elsewhere or pieces deemed "unfixable". Our heritage artisans specialize in difficult restorations other commercial retailers decline.',
		turnaroundTime: 'Same Day',
		benchMethod: 'Independent Master Goldsmith Diagnostic Review',
		startingPrice: 600,
		riskLevel: 'Minimal',
		assurances: ['Unbiased craftsmanship review', 'Non-destructive evaluation', 'Feasibility guarantee'],
	},
	{
		id: 'diagnostic-intake',
		category: 'inspection',
		categoryLabel: 'Inspection & Diagnostics',
		name: "I Don't Know What's Wrong (Diagnostic Triage)",
		tagline: 'Something feels loose, dull, distorted, or won’t clasp? Let our bench diagnose it',
		description: 'You do not need to know the technical terms. Simply describe what feels wrong, send a photo/video, or drop it off. Our master goldsmith will diagnose the root cause.',
		turnaroundTime: 'Same Day Diagnosis',
		benchMethod: 'Full Bench Triage, Gold Assay & Microscopic Gem Scan',
		startingPrice: 0,
		riskLevel: 'Minimal',
		assurances: ['Zero diagnostic fee if repaired', 'Photo explanation of problem', 'Transparent cost quote before work'],
		badge: 'Guided Intake',
	},
];

export const BENCH_TRUST_FACTORS = [
	{
		title: '0.001g Calibrated Balance',
		description: 'Gross and net gold weight recorded to 3 decimal places on calibrated Sartorius balances before and after bench work.',
		iconName: 'Scale',
	},
	{
		title: 'Laser Micro-Cold Welding',
		description: 'PUK 6 pulsed argon arc welding delivers pinpoint heatless joints, safe adjacent to emeralds, pearls, and enamels.',
		iconName: 'Sparkles',
	},
	{
		title: '10x Live HD Inspection',
		description: 'Watch your stones and hallmark laser inscriptions examined live on 4K salon monitors under stereomicroscopes.',
		iconName: 'Eye',
	},
	{
		title: 'Digital Vault Custody Passport',
		description: 'High-res photographic check-in receipt with timestamped weight logged into our secure atelier vault tracking system.',
		iconName: 'ShieldCheck',
	},
];
